name: gones_starter_kit
description: "My flutter starter kit."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: 1.0.8
  firebase_core: 3.0.0
  firebase_messaging: 15.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_secure_storage: 9.2.2
  freezed_annotation: 2.4.1
  go_router: 14.1.4
  json_annotation: 4.9.0
  riverpod_annotation: 2.3.5
  rxdart: 0.27.7

dev_dependencies:
  build_runner: 2.4.10
  flutter_test:
    sdk: flutter
  freezed: 2.5.3
  json_serializable: 6.8.0
  mocktail: 1.0.3
  riverpod_generator: 2.4.2
  very_good_analysis: 5.1.0

dependency_overrides: 
  meta: 1.14.0
  
flutter:
  uses-material-design: true
