import 'package:firebase_core/firebase_core.dart' hide FirebaseOptions;
import 'package:gones_starter_kit/firebase_options.dart';
import 'package:gones_starter_kit/utils/colored_debug_printer.dart';

/// Enum to define different environments
enum AppEnvironment {
  /// Development environment
  development,

  /// Production environment
  production
}

/// Class to store the environment information
abstract class EnvInfo {
  /// The current environment
  static AppEnvironment environment = AppEnvironment.development;

  /// Get the current firebase options based on the environment and platform.
  /// Generated by `flutterfire configure` — see lib/firebase_options.dart.
  static FirebaseOptions get firebaseOptions => DefaultFirebaseOptions.currentPlatform;

  /// Check if we are in production environment
  static bool get isProduction => environment == AppEnvironment.production;

  /// Describe the environment in the console
  static void describe() {
    Print.white(
      'ENVIRONMENT',
      ' ---------------------------------------------------------------------------------------',
    );

    Print.yellow(
      'ENVIRONMENT',
      ' | Environment      : $environment',
    );

    Print.white(
      'ENVIRONMENT',
      ' ---------------------------------------------------------------------------------------',
    );
  }
}
