{{#avec_firebase}}
import 'package:firebase_core/firebase_core.dart';
import 'package:{{app_name}}/firebase_options.dart';
{{/avec_firebase}}
import 'package:{{app_name}}/utils/colored_debug_printer.dart';

/// Enum to define different environments
enum AppEnvironment {
  /// Development environment
  development,

  /// Production environment
  production
}

/// Class to store the environment information
abstract class EnvInfo {
  /// The current environment
  static AppEnvironment environment = AppEnvironment.development;

  {{#avec_firebase}}
  /// Get the current firebase options. Generated by `flutterfire configure`.
  static FirebaseOptions get firebaseOptions => DefaultFirebaseOptions.currentPlatform;
  {{/avec_firebase}}

  /// Check if we are in production environment
  static bool get isProduction => environment == AppEnvironment.production;

  /// Describe the environment in the console
  static void describe() {
    Print.white('ENVIRONMENT', ' -------------------------------------------------------------------');
    Print.yellow('ENVIRONMENT', ' | Environment : $environment');
    Print.white('ENVIRONMENT', ' -------------------------------------------------------------------');
  }
}
