name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2

      - name: Write firebase_options.dart
        run: echo '{{ secrets.FIREBASE_OPTIONS }}' > lib/firebase_options.dart

      - name: Write GoogleService-info.plist
        run: echo '{{ secrets.GOOGLE_SERVICE_INFO_PLIST }}' > ios/Runner/GoogleService-Info.plist

      - name: Write google-services.json
        run: echo '{{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test
