name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: latest

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Login and select Firebase project
        run: firebase use "$FIREBASE_PROJECT_ID" --token ${{ secrets.FIREBASE_TOKEN }}

      - name: init Firebase
        run: firebase init

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test
