name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: latest

      - name: Firebase login
        uses: w9jds/firebase-action@master
        with:
          args: login
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      
      - name: Install Flutterfire CLI
        run: dart pub global activate flutterfire_cli

      - name: Configure Flutterfire
        run: flutterfire configure --yes --project=${{ secrets.FIREBASE_PROJECT_ID }} --android-package-name=com.gones.starterKit --ios-bundle-id=com.gones.starterKit

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test
